### ISSUE TITLE
Java is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by madorc** [aekrylov/vic2_economy_analyzer#15]
I have downloaded all the files directly and also manually in second attempt. I keep seeing the black box and this error whenever i click on the start file. Please help.

'Java is not recognized as an internal or external command, operable program or batch file'

**Comment by aekrylov** [comment]
Hey,
I've changed packaging, now the app should work as a regular exe file, see [latest release ](https://github.com/aekrylov/vic2_economy_analyzer/releases/tag/v0.14.1) for links. Please reopen the issue if it does not work for you

**Comment by madorc** [comment]
Who are you?
I don't recall
