### ISSUE TITLE
Potential data corruption in watcher?

### ISSUE THREAD

**Issue by Nashet** [aekrylov/vic2_economy_analyzer#8]
As I noticed watcher continues to work after closing all GUI windows. Like, from startme.bat. If user will close startme.bat in a moment of data writing than data probably will corrupted somewhere here

```
`private static void write(Watch watch, Path historyPath) throws IOException {
        Gson gson = new GsonBuilder().addSerializationExclusionStrategy(new NonSerializableExclusionStrategy())
                .create();

        String json = gson.toJson(watch, Watch.class);
        Files.write(historyPath, json.getBytes(), StandardOpenOption.TRUNCATE_EXISTING);
    }`

```
Is not it better to stop Watcher when user closes GUI, checking writing status before exit.

**Comment by aekrylov** [comment]
Yeah, watchers should be stopped when GUI is closed, and I fixed that. However, something may happen anyway while writing is performed, and this will lead to loss of pretty sensitive data, so I think backup files should be added (i.e. watcher writes to temporary file and only then replaces history file with temporary one).
